// ─── Universal Domains & Roles ────────────────────────────────────────────────
export const UNIVERSAL_DOMAINS: Record<string, string[]> = {
  "Technology & Engineering": [
    "Software Developer",
    "Data Scientist",
    "AI/ML Engineer",
    "Cybersecurity Analyst",
    "Cloud Architect",
    "DevOps Engineer",
    "Embedded Systems Engineer",
    "Robotics Engineer",
    "Civil Engineer",
    "Mechanical Engineer",
    "Electrical Engineer",
    "Chemical Engineer",
    "Biomedical Engineer",
    "Aerospace Engineer",
    "Environmental Engineer",
    "Network Engineer",
  ],
  "Business & Management": [
    "Business Analyst",
    "Product Manager",
    "Project Manager",
    "Management Consultant",
    "Operations Manager",
    "Supply Chain Manager",
    "HR Manager",
    "Entrepreneur",
    "Financial Analyst",
    "Investment Banker",
    "Actuary",
    "Risk Analyst",
    "Marketing Manager",
    "Brand Strategist",
    "Sales Manager",
    "Retail Manager",
  ],
  "Creative & Design": [
    "UX/UI Designer",
    "Graphic Designer",
    "Motion Designer",
    "Architect",
    "Interior Designer",
    "Fashion Designer",
    "Industrial Designer",
    "Game Designer",
    "Photographer",
    "Filmmaker",
    "Content Creator",
    "Art Director",
    "Illustrator",
    "Animator",
    "Creative Director",
    "Set Designer",
  ],
  "Science & Research": [
    "Research Scientist",
    "Biotechnologist",
    "Pharmacologist",
    "Chemist",
    "Physicist",
    "Astronomer",
    "Marine Biologist",
    "Neuroscientist",
    "Geologist",
    "Epidemiologist",
    "Forensic Scientist",
    "Materials Scientist",
    "Environmental Scientist",
    "Food Scientist",
    "Geneticist",
    "Microbiologist",
  ],
  "Healthcare & Medicine": [
    "Doctor (General)",
    "Surgeon",
    "Psychiatrist",
    "Dentist",
    "Pharmacist",
    "Physiotherapist",
    "Nurse",
    "Radiologist",
    "Nutritionist",
    "Veterinarian",
    "Occupational Therapist",
    "Paramedic",
    "Public Health Specialist",
    "Medical Researcher",
    "Clinical Psychologist",
    "Anesthesiologist",
  ],
  "Law & Policy": [
    "Lawyer",
    "Judge",
    "Public Prosecutor",
    "Corporate Lawyer",
    "Civil Rights Advocate",
    "Policy Analyst",
    "Diplomat",
    "IAS/IPS Officer",
    "Legal Consultant",
    "Compliance Officer",
    "Paralegal",
    "Arbitrator",
    "Intelligence Analyst",
    "Urban Planner",
    "Social Policy Researcher",
    "NGO Director",
  ],
  "Education & Social": [
    "Teacher",
    "Professor",
    "Education Consultant",
    "School Counselor",
    "Social Worker",
    "Community Organizer",
    "Nonprofit Manager",
    "Youth Worker",
    "Librarian",
    "Museum Curator",
    "Educational Content Creator",
    "Instructional Designer",
    "Child Psychologist",
    "Special Educator",
    "Academic Researcher",
    "Career Coach",
  ],
  "Media & Communication": [
    "Journalist",
    "News Anchor",
    "Podcast Host",
    "Public Relations Specialist",
    "Copywriter",
    "Technical Writer",
    "Editor",
    "Publisher",
    "Social Media Manager",
    "Digital Marketer",
    "SEO Specialist",
    "Advertising Executive",
    "Screenwriter",
    "Radio Jockey",
    "Documentary Filmmaker",
    "Communication Strategist",
  ],
  "Finance & Economics": [
    "Chartered Accountant",
    "Cost Accountant",
    "Tax Consultant",
    "Auditor",
    "Financial Planner",
    "Wealth Manager",
    "Economist",
    "Budget Analyst",
    "Credit Analyst",
    "Insurance Underwriter",
    "Stockbroker",
    "Forex Trader",
    "Microfinance Specialist",
    "Development Economist",
    "Quantitative Analyst",
    "CFO",
  ],
  "Arts & Culture": [
    "Musician",
    "Classical Dancer",
    "Theater Artist",
    "Stand-up Comedian",
    "Poet",
    "Novelist",
    "Sculptor",
    "Painter",
    "Art Restorer",
    "Cultural Journalist",
    "Heritage Curator",
    "Arts Administrator",
    "Film Critic",
    "Music Producer",
    "Choreographer",
    "Voice Artist",
  ],
  "Sports & Wellness": [
    "Professional Athlete",
    "Sports Coach",
    "Sports Psychologist",
    "Fitness Trainer",
    "Yoga Instructor",
    "Sports Nutritionist",
    "Physiotherapist",
    "Sports Manager",
    "Adventure Sports Guide",
    "Esports Professional",
    "Sports Journalist",
    "Athletic Director",
  ],
  "Trades & Skilled Work": [
    "Chef / Culinary Artist",
    "Sommelier",
    "Event Manager",
    "Wedding Planner",
    "Real Estate Agent",
    "Travel Consultant",
    "Hotel Manager",
    "Flight Attendant",
    "Pilot",
    "Merchant Navy Officer",
    "Electrician (Master)",
    "CNC Machinist",
    "Carpenter",
    "Jewellery Designer",
    "Tattoo Artist",
    "Wedding Photographer",
  ],
};

export const FIELDS_OF_STUDY: Record<string, string[]> = {
  "Arts & Humanities": [
    "Literature",
    "History",
    "Philosophy",
    "Fine Arts",
    "Music",
    "Theatre",
    "Linguistics",
    "Archaeology",
    "Cultural Studies",
  ],
  "Commerce & Business": [
    "Commerce",
    "Accounting",
    "Economics",
    "Business Administration",
    "Finance",
    "Marketing",
    "International Business",
  ],
  Science: [
    "Physics",
    "Chemistry",
    "Biology",
    "Mathematics",
    "Statistics",
    "Computer Science",
    "Biotechnology",
    "Environmental Science",
  ],
  Engineering: [
    "Computer Engineering",
    "Mechanical Engineering",
    "Civil Engineering",
    "Electrical Engineering",
    "Electronics Engineering",
    "Chemical Engineering",
    "Aerospace Engineering",
    "Biomedical Engineering",
    "Marine Engineering",
  ],
  "Medicine & Health": [
    "MBBS",
    "Nursing",
    "Pharmacy",
    "Physiotherapy",
    "Dentistry",
    "Veterinary",
    "Public Health",
    "Nutrition & Dietetics",
  ],
  Law: ["LLB", "BA LLB", "Corporate Law", "International Law"],
  "Design & Architecture": [
    "Architecture",
    "Interior Design",
    "Fashion Design",
    "Graphic Design",
    "Industrial Design",
  ],
  "Social Sciences": [
    "Psychology",
    "Sociology",
    "Political Science",
    "Anthropology",
    "Social Work",
    "Education",
  ],
  Management: [
    "MBA",
    "BBA",
    "Hotel Management",
    "Event Management",
    "Sports Management",
  ],
  "Vocational & Trades": [
    "Culinary Arts",
    "Tourism & Hospitality",
    "Aviation",
    "Maritime Studies",
  ],
};

export const FIELD_TO_SKILL_CATEGORY: Record<string, string> = {
  "Computer Engineering": "tech",
  "Computer Science": "tech",
  "Electronics Engineering": "tech",
  "Electrical Engineering": "tech",
  "Mechanical Engineering": "engineering",
  "Civil Engineering": "engineering",
  "Aerospace Engineering": "engineering",
  "Biomedical Engineering": "engineering",
  "Chemical Engineering": "engineering",
  "Marine Engineering": "engineering",
  Literature: "arts",
  History: "arts",
  Philosophy: "arts",
  "Fine Arts": "arts",
  Music: "arts",
  Theatre: "arts",
  Linguistics: "arts",
  Archaeology: "arts",
  "Cultural Studies": "arts",
  Commerce: "commerce",
  Accounting: "commerce",
  Economics: "commerce",
  "Business Administration": "commerce",
  Finance: "commerce",
  Marketing: "commerce",
  "International Business": "commerce",
  MBA: "commerce",
  BBA: "commerce",
  Physics: "science",
  Chemistry: "science",
  Biology: "science",
  Mathematics: "science",
  Statistics: "science",
  Biotechnology: "science",
  "Environmental Science": "science",
  MBBS: "medicine",
  Nursing: "medicine",
  Pharmacy: "medicine",
  Physiotherapy: "medicine",
  Dentistry: "medicine",
  Veterinary: "medicine",
  "Public Health": "medicine",
  "Nutrition & Dietetics": "medicine",
  LLB: "law",
  "BA LLB": "law",
  "Corporate Law": "law",
  "International Law": "law",
  Architecture: "design",
  "Interior Design": "design",
  "Fashion Design": "design",
  "Graphic Design": "design",
  "Industrial Design": "design",
  Psychology: "social",
  Sociology: "social",
  "Political Science": "social",
  Anthropology: "social",
  "Social Work": "social",
  Education: "social",
  "Hotel Management": "hospitality",
  "Event Management": "hospitality",
  "Sports Management": "sports",
  "Culinary Arts": "trades",
  "Tourism & Hospitality": "trades",
  Aviation: "trades",
  "Maritime Studies": "trades",
};

export const FIELD_SKILL_MAP: Record<string, string[]> = {
  tech: [
    "Python",
    "JavaScript",
    "Java",
    "C++",
    "React",
    "Node.js",
    "SQL",
    "Machine Learning",
    "Cloud (AWS/Azure)",
    "Docker",
    "Git",
    "System Design",
    "TypeScript",
    "MongoDB",
    "REST APIs",
    "Cybersecurity Basics",
  ],
  engineering: [
    "AutoCAD",
    "MATLAB",
    "SolidWorks",
    "ANSYS",
    "Project Management",
    "Thermodynamics",
    "Structural Analysis",
    "PLC Programming",
    "Technical Drawing",
    "Quality Control",
    "CAD/CAM",
    "Circuit Design",
  ],
  arts: [
    "Creative Writing",
    "Research & Analysis",
    "Public Speaking",
    "Critical Thinking",
    "Content Creation",
    "Editing",
    "Translation",
    "Scriptwriting",
    "Storytelling",
    "Journalism",
    "Cultural Analysis",
    "Grant Writing",
  ],
  commerce: [
    "Financial Accounting",
    "MS Excel",
    "Tally",
    "Business Communication",
    "Market Research",
    "Sales",
    "Negotiation",
    "Data Analysis",
    "GST/Taxation",
    "Financial Modeling",
    "PowerBI",
    "Business Strategy",
  ],
  science: [
    "Research Methodology",
    "Statistical Analysis",
    "Lab Techniques",
    "Data Visualization",
    "Scientific Writing",
    "Python/R",
    "SPSS",
    "Literature Review",
    "Experimental Design",
    "Grant Writing",
  ],
  medicine: [
    "Patient Communication",
    "Clinical Assessment",
    "Medical Documentation",
    "Research Methodology",
    "First Aid",
    "Pharmacology Basics",
    "Diagnostic Skills",
    "Medical Ethics",
    "Public Health Knowledge",
    "Electronic Health Records",
  ],
  law: [
    "Legal Research",
    "Case Analysis",
    "Contract Drafting",
    "Negotiation",
    "Argumentation",
    "Legal Writing",
    "Moot Court",
    "Statutory Interpretation",
    "Client Communication",
    "Compliance Knowledge",
  ],
  design: [
    "Adobe Photoshop",
    "Illustrator",
    "Figma",
    "AutoCAD",
    "SketchUp",
    "Typography",
    "Color Theory",
    "3D Modeling",
    "UI Prototyping",
    "Brand Identity",
    "User Research",
    "InDesign",
  ],
  social: [
    "Survey Design",
    "Qualitative Research",
    "Counseling Skills",
    "Report Writing",
    "Community Engagement",
    "Data Interpretation",
    "Policy Analysis",
    "Grant Writing",
    "Program Evaluation",
    "Crisis Intervention",
  ],
  hospitality: [
    "Event Planning",
    "Customer Service",
    "Budget Management",
    "Vendor Management",
    "F&B Knowledge",
    "Hospitality Software",
    "Crisis Management",
    "Marketing & PR",
    "Team Leadership",
  ],
  sports: [
    "Sports Coaching",
    "Fitness Assessment",
    "Nutrition Planning",
    "Sports Psychology",
    "Performance Analysis",
    "Sports Management",
    "First Aid & Injury Prevention",
    "Team Coordination",
  ],
  trades: [
    "Culinary Techniques",
    "Menu Planning",
    "Food Safety & Hygiene",
    "Customer Relations",
    "Supply Chain",
    "Cost Control",
    "International Cuisine",
    "Plating & Presentation",
  ],
};

export const UNIVERSAL_SOFT_SKILLS = [
  "Communication",
  "Problem Solving",
  "Teamwork",
  "Time Management",
  "Adaptability",
  "Leadership",
];

export const KNOWN_LANGUAGES = [
  "English",
  "Hindi",
  "Tamil",
  "Telugu",
  "Kannada",
  "Malayalam",
  "Bengali",
  "Marathi",
  "Gujarati",
  "Punjabi",
  "Odia",
  "Urdu",
  "French",
  "German",
  "Spanish",
  "Mandarin",
  "Japanese",
  "Arabic",
];

export const ACTIVITIES = [
  { id: "logic", label: "Solving logical problems", icon: "🧩" },
  { id: "building", label: "Building / making things", icon: "🔨" },
  { id: "writing", label: "Writing and storytelling", icon: "✍️" },
  { id: "helping", label: "Helping people", icon: "🤝" },
  { id: "leading", label: "Leading and organizing", icon: "🎯" },
  { id: "data", label: "Analyzing data & patterns", icon: "📊" },
  { id: "art", label: "Creating visual art", icon: "🎨" },
  { id: "performing", label: "Performing on stage", icon: "🎭" },
  { id: "nature", label: "Working with nature", icon: "🌿" },
  { id: "teaching", label: "Teaching and explaining", icon: "📚" },
  { id: "research", label: "Researching & discovering", icon: "🔬" },
  { id: "debating", label: "Debating and arguing", icon: "⚖️" },
  { id: "cooking", label: "Cooking and crafting", icon: "🍳" },
  { id: "sports", label: "Playing or coaching sports", icon: "⚽" },
  { id: "tech", label: "Working with technology", icon: "💻" },
  { id: "caring", label: "Caring for others", icon: "❤️" },
  { id: "trading", label: "Trading and negotiating", icon: "💼" },
  { id: "design", label: "Designing and aesthetics", icon: "✨" },
  { id: "coding", label: "Coding and automating", icon: "⚙️" },
  { id: "outdoors", label: "Exploring outdoors", icon: "🏔️" },
  { id: "finance", label: "Managing finances", icon: "💰" },
  { id: "networking", label: "Communicating & networking", icon: "🌐" },
  { id: "animals", label: "Working with animals", icon: "🐾" },
  { id: "culture", label: "Cultural & heritage work", icon: "🏛️" },
];

export const WORK_ENVIRONMENTS = [
  "Fast-paced startup",
  "Large structured organization",
  "Working independently",
  "Field / outdoor work",
  "Creative studio",
  "Hospital or clinic",
  "Research lab",
  "Classroom or campus",
  "Government or public sector",
  "Remote / freelance",
  "Own business",
  "International environment",
];

export const MOTIVATORS = [
  "Financial security",
  "Creative expression",
  "Helping society",
  "Recognition and status",
  "Intellectual challenge",
  "Work-life balance",
  "Building something new",
  "Stability and routine",
  "Global impact",
  "Continuous learning",
];

export const INTENT_REASONS = [
  "It pays well",
  "I'm passionate about it",
  "Family / societal expectation",
  "I'm good at it",
  "It has job security",
  "Someone I admire does it",
  "I studied for it",
  "I want to help people through it",
  "It gives me creative freedom",
];

export const PERSONALITY_QUESTIONS = [
  {
    id: "q1",
    question: "When solving problems, I prefer:",
    a: "Logical step-by-step analysis",
    b: "Creative experimentation",
  },
  {
    id: "q2",
    question: "I work better:",
    a: "Alone with deep focus",
    b: "With people and collaboration",
  },
  {
    id: "q3",
    question: "I'm drawn more to:",
    a: "Abstract ideas and theory",
    b: "Practical hands-on work",
  },
  {
    id: "q4",
    question: "Under pressure I tend to:",
    a: "Stay calm and methodical",
    b: "Move fast and adapt on the fly",
  },
  {
    id: "q5",
    question: "I prefer feedback that is:",
    a: "Direct and blunt",
    b: "Thoughtful and encouraging",
  },
  {
    id: "q6",
    question: "My decisions are more:",
    a: "Data and logic driven",
    b: "Values and feeling driven",
  },
  {
    id: "q7",
    question: "I find meaning in work that:",
    a: "Creates measurable impact",
    b: "Expresses who I am",
  },
  {
    id: "q8",
    question: "Long term I see myself as:",
    a: "An expert in one deep area",
    b: "A generalist who connects many fields",
  },
];

export const EDUCATION_LEVELS = [
  "High School / 12th Grade",
  "Undergraduate (pursuing)",
  "Graduate / Postgraduate",
  "Completed — Working",
  "Self-taught / No formal degree",
];
